### ISSUE TITLE
How to save current checkpoint and continue optimization process?

### ISSUE THREAD

**Issue by ekorudiawan** [CMA-ES/pycma#126]
I used pycma to optimize some parameters on the robot simulation model, that need to run the simulation model to get fitness value. So, it took very long time to get the result.
Is it possible to save current optimization result and continue the optimization process from the last checkpoint?

**Comment by nikohansen** [comment]
Hi, sorry for the late answer. Yes, it should be easily possible via `pickle`. You may want to search for `pickle` in the [help of `cma.CMAEvolutionStrategy`](http://cma.gforge.inria.fr/apidocs-pycma/cma.evolution_strategy.CMAEvolutionStrategy.html). The latest release `3.0.1` provides also a [`CMAEvolutionStrategy.pickle_dumps`](http://cma.gforge.inria.fr/apidocs-pycma/cma.evolution_strategy.CMAEvolutionStrategy.html#pickle_dumps) method with description of usage.

**Comment by Saksham-Katiyar** [comment]
I have a very similar issue to this. I am using pycma to optimize some parameters for robot simulation which take a lot of time and I would like to save the results.

Please note the following points:
- I am using the [pickle_dumps()](https://cma-es.github.io/apidocs-pycma/cma.evolution_strategy.CMAEvolutionStrategy.html#pickle_dumps) method to save the `es` object and pickle library to load the pickle object
- I am using `while not es.stop()` loop for optimization which is supposed to terminate because of `maxiter` condition being satisfied (which is actually happening)

So I perform the following steps in order:
- Execute the optimization loop (which terminates correctly until `maxiter` condition is reached, say 100 for example)
- Save the results using `es.pickle_dumps()`
- Load the previous results using pickle library
- Change the `maxiter` value using `es.opts.set({'maxiter': 120})`
- Execute the similar loop again using `while not es.stop()` condition

**Issue**: The loop terminates at the earlier value of `maxiter` i.e. 100 instead of 120. It seems as if the `maxiter` value is not updated.

- I can see the log which prints `termination on maxiter=100` (along with other details) which guarantees that the `es` object is correctly saved and loaded using pickle. And that the `maxiter` is not updated for some reason.
- I inspected the `versatile_options()` of the object and found `maxiter` in the list which means it is one the options which I should be able to change

Any help regarding possible solutions will be genuinely appreciated !!

**Comment by nikohansen** [comment]
Thanks for the detailed information. This seems indeed strange, but it is the "correct" behavior, because some termination conditions do not continue to fire all the time. There is a simple fix: before you execute the `while not es.stop()` loop the second time, you must call
```python
    es.stop().clear()
```
which removes the active termination condition. See also

```python
es.stop??

Signature:
es.stop(
    check=True,
    ignore_list=(),
    check_in_same_iteration=False,
    get_value=None,
)
Docstring:
return the termination status as dictionary.

With ``check == False``, the termination conditions are not checked
and the status might not reflect the current situation.
``check_on_same_iteration == False`` (new) does not re-check during
the same iteration. When termination options are manually changed,
it must be set to `True` to advance afterwards.
``stop().clear()`` removes the currently active termination
conditions.

As a convenience feature, keywords in `ignore_list` are removed from
the conditions.

If `get_value` is set to a condition name (not the empty string),
`stop` does not update the termination dictionary but returns the
measured value that would be compared to the threshold. This only
works for some conditions, like 'tolx'. If the condition name is
not known or cannot be computed, `None` is returned and no warning
is issued.
```
