### ISSUE TITLE
Deprecation warning due to invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [CMA-ES/pycma#144]
Deprecation warnings are raised due to invalid escape sequences. This can be fixed by using raw strings or escaping the literals. pyupgrade also helps in automatic conversion : https://github.com/asottile/pyupgrade/

```
find . -iname '*.py' | grep -Ev 'vendor|example|doc|tools|sphinx' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./cma/logger.py:1570: DeprecationWarning: invalid escape sequence \s
  """log an arbitrary number of data (a data row) per "timestep".
```

**Comment by nikohansen** [comment]
Thanks for the catch. The problem is the usage of a raw string `r'lg($\sigma$)'` in a code example in the docstring, [line 1605](https://github.com/CMA-ES/pycma/blob/a47716cf126d98eeb709565888ea3f8d36daa240/cma/logger.py#L1605).

```python
...                 labels=['best f', 'lg(best f)', r'lg($\sigma$)'])
```

Defining the docstring with `r"""` as recommended [here](https://www.python.org/dev/peps/pep-0257/#what-is-a-docstring) should fix it.
