### ISSUE TITLE
Global seed in CMA-ES

### ISSUE THREAD

**Issue by yhl48** [CMA-ES/pycma#221]
When a seed is set for CMA-ES with the `inopts` argument, the seed is set globally. Upon inspection of the code, if I am not mistaken, `np.random.seed()` is used to set the seed. However, this could lead to undesired outcomes when CMA-ES is used as part of a larger codebase. Would it be possible to change it to a local seed?

**Comment by nikohansen** [comment]
Right, undesired side effects can even happen when the seed is not changed, because calling the random generator will change the sequence or "random" events in other parts of the codebase.

I believe the best (only?) way to prevent this is to pass/change the desired random number generator via the `'randn'` option and set the `'seed'` option to `np.nan` such that the seed of `np.random` is not touched.

```python
import cma
cma.CMAOptions('rand')
{'randn': 'np.random.randn  #v randn(lam, N) must return an np.array of shape (lam, N), see also cma.utilities.math.randhss',
 'seed': 'time  # random number seed for `numpy.random`; `None` and `0` equate to `time`, `np.nan` means "do nothing", see also option "randn"'}
```

**Comment by yhl48** [comment]
Thanks, deactivating `seed` does solve the problem. However, could you please clarify what 'randn' does? I was hoping that the CMA-ES results are replicable with 'randn' being set, is that the case? and how should I set the dimension of 'randn'?

**Comment by nikohansen** [comment]
Deactivating the seed means that repeated runs won't give different solutions, which is somehow not the expected result for a randomized algorithm.

As the above documentation writes: `randn` is a function that (must) return(s) an `np.array` of shape `(lam, N)`.

Usually, each entry of this array is (0,1) standard normally distributed like for `np.random.randn` which is the default value for `randn`.

I don't know what "replicable" means in your question and whether this is so depends on what the user sets `randn` to rather than on the `cma` module. Unfortunately, I have also seen obscure differences in behavior when using the same seed on different computers.

**Comment by LennartPurucker** [comment]
Hi @nikohansen, could you elaborate on this "usually"? 

> Deactivating the seed means that repeated runs will **(usually)** not give different solutions

I am trying to make my usage of cma replicable in the sense that I can obtain the same results given the same global seed. 

But the results differ no matter how I set "rand", "seed", or the global numpy seed. But only for the code I use in my specific application, which never touches/changes the random state. 

It works fine in a test example where I am only using cma the exact same way.

**Comment by nikohansen** [comment]
I may have misspoken, "do nothing" with the seed (`seed=Nan`) doesn't really mean to get always the same result (as the seed state depends on previous runs). Rather, setting the seed to the same given value, like `seed=22` or `'seed': 22`, should give the same result each and every time which seems to be what you are asking for.

**Comment by LennartPurucker** [comment]
I see, thank you very much. 

One follow-up question:

Is this similar when using the ask()/tell() interface, or does this introduce any complications?

**Comment by nikohansen** [comment]
This should indeed be the same with the ask-and-tell interface because these options are passed to the `CMAEvolutionStrategy` class.
