### ISSUE TITLE
Feeding in solutions from a previous optimisation run

### ISSUE THREAD

**Issue by trbedwards** [CMA-ES/pycma#242]
I have a previous optimisation run that I would like to feed in solutions and function values from, to give CMA-ES a warm-start. This previous optimisation might not have necessarily been run using pycma.

Is there a way to do this? I've tried to use `inject(x_best)` from my best solution so far but after calling a few `ask`s and `tell`s, it throws the following error:
`ValueError: Found unused injected direction/solutions`

**Comment by nikohansen** [comment]
Generally, this is what the arguments `X0` and `sigma` are for. If we assume `X0` is already a pretty good guess, we use a small value for `sigma`.

When a full run from CMA-ES should be continued, the [`feed_for_resume`](https://cma-es.github.io/apidocs-pycma/cma.evolution_strategy.CMAEvolutionStrategy.html#feed_for_resume) method, see also https://github.com/CMA-ES/pycma/issues/240, "re-creates" a previous run from solutions and f-values which is also "directly" possible using the ask-and-tell interface. These depend on the population size `popsize` of the current CMA-ES instance to be the same as the one how the data were generated. If the solutions to be fed were not sampled during a run from CMA-ES, this is bound to fail, because the algorithm assumes a particular sample distribution. In this case passing the found best guess as initial solution with a small initial step-size seems the best approach.

Specifically, it's hard to understand the above error without additional information. The calling code to be used would be a first step. Generally, it should be possible to inject one or a few solutions in each iteration without getting an error.
