### ISSUE TITLE
Non scalar values for sigma0?

### ISSUE THREAD

**Issue by jasonzliang** [CMA-ES/pycma#27]
I am curious as to why only scalar values for sigma0 are allowed. It seems that there shouldnt be any reason why we cannot not have a vector of sigma0 values for each dimension of the optimization problem.

In fact this is possible in the java implementation of CMA-ES: 

https://commons.apache.org/proper/commons-math/javadocs/api-3.1/org/apache/commons/math3/optim/nonlinear/scalar/noderiv/CMAESOptimizer.Sigma.html

**Comment by nikohansen** [comment]
The reason is that the same can be preferably achieved by transformation of the objective function using `cma.fitness_transformations.ScaleCoordinates`:

```python
import cma 
ScaleCoordinates = cma.fitness_transformations.ScaleCoordinates
felli_3d_scaled = ScaleCoordinates(cma.ff.elli, [100, 10, 1])
assert felli_3d_scaled([0.01, 0.1, 1]) == cma.ff.elli([1, 1, 1])
cma.fmin(felli_3d_scaled, [1, 1, 1], 1)
cma.plot()
```
<img width="622" alt="screen shot 2017-08-27 at 10 28 50" src="https://user-images.githubusercontent.com/7316439/29748250-9daafc98-8b12-11e7-85a8-ef8935a07157.png">

In this example the mis-scaling of the ellipsoid function is reduced to 10 (= 1000/100). The disadvantage of rescaling the initial covariance matrix is that there is a numerical limit to the condition number of the covariance matrix. Even if we start with the identity, in my experience we may end up close or beyond these limits in a practical application (like in issue #10). Hence rescaling the objective function is the preferable approach. 

Still, the module gives also the possibility for an additional scaling in the distribution or for changing the initial covariance matrix. 

```python
cma.s.pprint(cma.CMAOptions('stds'))

{'CMA_stds': 'None  # multipliers for sigma0 in each coordinate, not represented in C, makes scaling_of_variables obsolete',
 'CMA_teststds': 'None  # factors for non-isotropic initial distr. of C, mainly for test purpose, see CMA_stds for production',
 'scaling_of_variables': 'None  # depreciated, rather use fitness_transformations.ScaleCoordinates instead (or possibly CMA_stds).\n            Scale for each variable in that effective_sigma0 = sigma0*scaling. Internally the variables are divided by scaling_of_variables and sigma is unchanged, default is `np.ones(N)`'}
```

**Comment by jasonzliang** [comment]
Thanks for the explanation. If I wish to use 'CMA_stds' with the objective function in the example above, should I use [100, 10, 1] as the multipliers for each dimension?

**Comment by jasonzliang** [comment]
r

**Comment by nikohansen** [comment]
Please check out these [Practical Hints](http://cma.gforge.inria.fr/cmaes_sourcecode_page.html#practical). Regarding the multipliers, I think so, but it is always worth while to double (or triple) check whether a factor or its inverse is needed (or possibly the square of square root, if variances are involved).
