### ISSUE TITLE
No linear transformation interval in box constraint handling?

### ISSUE THREAD

**Issue by youheiakimoto** [CMA-ES/pycma#40]
https://github.com/CMA-ES/pycma/blob/881ad335a5c446a89752a279e47179472f9e7bb2/cma/transformations.py#L267

In the docstring, it is said that the linear part takes about 90 % of the feasible interval in typical cases, however, au = al = (ub - lb) / 2 result in transforming whole region quadratically. I guess they should be au = al = (ub - lb) / 20.

**Comment by nikohansen** [comment]
Thanks for checking this. I assume the code is correct, in the sense that it is meant to be as it is and there is a reason for it (IIRC it was written with quite some care for somewhat pathological corner cases). The docstring apparently covers the case where `ub - lb` is not much smaller than one. The documentation also says (though there is an incomplete sentence)

https://github.com/CMA-ES/pycma/blob/881ad335a5c446a89752a279e47179472f9e7bb2/cma/transformations.py#L185
_Partly due to numerical considerations depend the values ``al`` and 
    ``au`` on ``abs(lb)`` and ``abs(ub)`` which makes the
    transformation non-translation invariant. In particular increases the
    interval In contrast to ``sin(.)``,
    the transformation is robust to "arbitrary" values for boundaries,
    e.g. a lower bound of ``-1e99`` or ``np.Inf`` or ``None``._

AFAICS, the reason for this apparent weird choice is possible numerical discretization errors (apart from the original conflicting goals to (i) ideally have the identity but also (ii) have a smooth function). I can't say for sure without taking more time to investigate, but if `lb=2000` and `ub=2000.1` the code probably takes a numerically more robust approach.

**Comment by youheiakimoto** [comment]
I see the point. The point that I misunderstood is that the cases au = al = (ub - lb) / 2 are not the typical cases. The equality au (or al) = (ub - lb) / 2 only when ub and lb have the same sign and |ub - lb| < (1 + |lb| (or |ub|)) / 10 hold. In short, al = (1 + |lb|)/20 and au = (1 + |ub|) / 20 is the typical choice and then about 90% of the feasible interval is linearly mapped.

At first glance, it looked a bit wired, but knowing that the floating point numbers system is not translation invariant in a exact sense and the discretization error depends on the absolute value of a number, what this algorithm does looks reasonable to me now.
