### ISSUE TITLE
pycma always seeds np.random

### ISSUE THREAD

**Issue by MichaelClerx** [CMA-ES/pycma#54]
The current code either seeds `np.random` with a user specified seed, or a new random seed:

https://github.com/CMA-ES/pycma/blob/master/cma/evolution_strategy.py#L1359-L1364

This means that if the user seeds `np.random`, then generates random samples, then calls cma, and then generates more samples, the code still produces arbitrary output.

A workaround is to always pass a seed to cma, but it seems to me that changing the state of `numpy.random` (unless asked specifically) is a side-effect that should be eliminated

**Comment by nikohansen** [comment]
Thanks, this is indeed a semi-bug, because it is now possible to pass any random number generator via the `'randn'` option (default is `numpy.random.randn`). The seed should not be changed if any other generator than `np.random.randn` is used. 

On the other hand, if `np.random.randn` is used, I don't see how to prevent any side effects and I like the functionality that the seed is chosen time-dependent by default.

**Comment by MichaelClerx** [comment]
`np.random.randn` is seeded by default, you don't need to do it yourself unless you want to fix the seed

**Comment by nikohansen** [comment]
Good point. Now I see though that the advantage to seed the generator again is that then the run is easily reproducible: the seed is printed out with the initial message and can be (re-)used for this very purpose. I don't know how I could compute a "printable" seed from the random state without (re-)seeding the generator. I think this is the main reason why it was implemented like it is.

**Comment by nikohansen** [comment]
The side effect can now (since `v2.5.4`) be prevented using `np.nan` as value for `'seed'` in `CMAOptions`. Also, the seed of `np.random` will only be touched if the `'randn'` option is set to `np.random.randn` (as it is by default).
