### ISSUE TITLE
Keeping some survivors between generations

### ISSUE THREAD

**Issue by mfagerlund** [CMA-ES/pycma#74]
Hi, in my personal version of CmaEs I tried to keep samples longer than for a single generation. Typically, the fitness computation will take a significant amount of time so if we can re-use it then that's great.

If I keep all of one generation into the next generation and keep the top X% by fitness, convergence suffers. But if I only let them stay around for a single extra generation, convergence picks up and it's for free.

Running Rosenbrock with 8 dimensions over 1000 runs I get these results

*with* keep survivors
1000: t=18.9ms, evals=4195.2, hits=100.00 %

*without* keep survivors
1000: t=20.9ms, evals=4870.7, hits=100.00 %

Meaning a 13+% of evaluation reduction and both converge 100% of the time.

any thoughts?

Notice how the time is roughly the same, that's because fitness evaluations are almost free for this problem, but typically they won't be.

mattias

**Comment by nikohansen** [comment]
Some random thoughts:
- Reusing solutions may violate some unbiasedness/stationary conditions because the samples stem from a different distribution
- IIRC there has been done some work on reusing and consequently re-weighting samples in the context of Natural Evolution Strategies, see e.g. Sect 3.2, p959 [here](http://www.jmlr.org/papers/volume15/wierstra14a/wierstra14a.pdf).
- My personal experiments with reusing samples has not been encouraging enough to take it on as default, but I don't have any precise data to argue with.
- I would be surprised if we wouldn't find an example where we lose more than the improvement you observed on the Rosenbrock function. Then we have to make decisions which scenario is more important.
- In general, this is related to [injection of directions or solutions](https://arxiv.org/abs/1110.4181). I believe the current code supports optionally elitist re-injection already. The `CMAEvolutionStrategy` class also has an `inject` method which, IIRC, accounts for the bias problem.
